version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: Artists
      - name: Albums
      - name: Tracks
      - name: Genres
      - name: TrackGenres
      - name: Audio
      - name: Social
      - name: Labels
      - name: ArtistLabels
      - name: Composers
      - name: Lyricists
      - name: TrackComposers
      - name: TrackLyricists